### ISSUE TITLE
Cannot find Call summary bot app in the app store

### ISSUE THREAD

**Issue by jdaviescoates** [nextcloud/call_summary_bot#18]
I've got various installs of Nextcloud, all running 27.1.0, but nothing comes up when I search for Call summary bot :( 

Is that just because it's still rc.2?

**Comment by svtcpx** [comment]
Confirmed, same here. Can't wait for this to come out, very useful indeed!

**Comment by nickvergessen** [comment]
> Is that just because it's still rc.2?

Could be. Totally forgot about this.

Will send a new version soon.

**Comment by nickvergessen** [comment]
Also sorry for not replying at all. It turned out I used by script to generate this repo and that makes me unsubscribe by default unless mentioned, but since I maintain this app I should have been subscribed.

I also fixed that now.

Release is available in https://apps.nextcloud.com/apps/call_summary_bot

**Comment by jdaviescoates** [comment]
> Release is available in https://apps.nextcloud.com/apps/call_summary_bot

Great, thanks!

I'm not seeing it when I search within my Nextcloud yet, but presumably it'll appear there in due course....

Thanks again.

**Comment by nickvergessen** [comment]
Yeah, I think the caching inbetween can be up to 6h
